version: '2.1'
services:
    ldap-mailcow:
        image: programmierus/ldap-mailcow
        container_name: mailcowcustomized_ldap-mailcow
        depends_on:
            - nginx-mailcow
        volumes:
            - ./data/ldap:/db:rw
            - ./data/conf/dovecot:/conf/dovecot:rw
            - ./data/conf/sogo:/conf/sogo:rw
        environment:
            - LINUXMUSTER_MAILCOW_LDAP_URI=<YOUR-AD-URI>
            - LINUXMUSTER_MAILCOW_LDAP_BASE_DN=<YOUR-BASE-DN>
            - LINUXMUSTER_MAILCOW_LDAP_BIND_DN=<YOUR-BIN-DN>
            - LINUXMUSTER_MAILCOW_LDAP_BIND_DN_PASSWORD=<YOUR-PASSWORD>
            - LINUXMUSTER_MAILCOW_API_KEY=<SOME-API-KEY>
            - LINUXMUSTER_MAILCOW_SYNC_INTERVAL=300
            # OPTIONAL:
            - LINUXMUSTER_MAILCOW_API_HOST="https://nginx-mailcow"
            - LINUXMUSTER_MAILCOW_DOCKERAPI_HOST="https://dockerapi-mailcow"
        networks:
          mailcow-network:
            aliases:
              - ldap